language: android
sudo: required
jdk: oraclejdk8

before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
  -$HOME/.gradle/caches/
  -$HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
 
branches:
 only: 
  - master

android:
 components:
# - tools
# - platform-tools
# - build-tools-$ANDROID_BUILD_TOOLS
# - android-$EMULATOR_API_LEVEL
# - android-$ANDROID_API
# - extra-google-m2repository
# - extra-android-m2repository # for design library
# - tools
 
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$EMULATOR_API
 - android-$ANDROID_API
 - sys-img-armeabi-v7a-android-$EMULATOR_API
 - sys-img-armeabi-v7a-android-tv-$EMULATOR_API
# - add-on
# - extra
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- ./gradlew dependencies || true
 
# when a different device is needed, take a look into the following command, for getting available sdk and targets
# android list sdk --all --extended
#- echo no | android create avd -n test -k "system-images;android-22;android-tv;armeabi-v7a"

# Emulator Management: Create, Start and Wait
before_script:
- android list target
- echo no | android create avd --force -n test -t android-22 -g android-tv --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

# script:
# - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
